// Generated by CoffeeScript 2.7.0
(function() {
  var env, findTags, includeSpecsWithoutTags, includedTags, jasmine, originalFilter;

  jasmine = require('@lumine-code/jasmine-focused');

  env = jasmine.getEnv();

  includeSpecsWithoutTags = true;

  env.includeSpecsWithoutTags = function(permit) {
    return includeSpecsWithoutTags = permit;
  };

  includedTags = [];

  env.setIncludedTags = function(tags) {
    return includedTags = tags;
  };

  findTags = function(spec) {
    var parent, ref, tags, word, words;
    words = spec.description.split(' ');
    tags = (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = words.length; i < len; i++) {
        word = words[i];
        if (word.indexOf('#') === 0) {
          results.push(word.substring(1));
        }
      }
      return results;
    })();
    if (tags == null) {
      tags = [];
    }
    if (parent = (ref = spec.parentSuite) != null ? ref : spec.suite) {
      return tags.concat(findTags(parent));
    } else {
      return tags;
    }
  };

  originalFilter = env.specFilter ? env.specFilter : function() {
    return true;
  };

  env.specFilter = function(spec) {
    var tags;
    if (!originalFilter(spec)) {
      return false;
    }
    tags = findTags(spec);
    if (includeSpecsWithoutTags && tags.length === 0) {
      return true;
    }
    if (tags.some(function(t) {
      return includedTags.some(function(it) {
        return it === t;
      });
    })) {
      return true;
    } else {
      return false;
    }
  };

  module.exports = jasmine;

}).call(this);
